### ISSUE TITLE
hdpGLM fails when grouped tibble provided

### ISSUE THREAD

**Issue by stnorton** [DiogoFerrari/hdpGLM#1]
Small issue, but the error message dplyr provides here is very unhelpful.

I accidentally saved a dataframe as `grouped_df` class. When provided as a data argument to `hdpGLM` it returns this error:
`Error in filter_impl(.data, quo) : Result must have length 187, not 3298`

Given that `dplyr::ungroup()` is relatively easy to forget while cleaning data (for me at least), it might be helpful to at least have a clearer/earlier error message. Especially since dplyr throws this error message when attempting to use undeclared variables, which could lead users in the wrong direction.

**Comment by DiogoFerrari** [comment]
Done !
