### ISSUE TITLE
User cannot specify y axis labels for `plot.hdpGLM`

### ISSUE THREAD

**Issue by stnorton** [DiogoFerrari/hdpGLM#4]
A nice enhancement would be for users to be able to supply their own labels for context IDs for the plot. Currently, the `context.id` argument just pulls the context labels as they are in the data, which aren't always formatted nicely (or in my case, are in a language other than English). Currently this can only be accomplished by recoding the labels in the data and rerunning the model.

**Comment by DiogoFerrari** [comment]
Good idea

**Comment by DiogoFerrari** [comment]
I am closing this issue. For now, I will modify the documentation advising pre-processing of the context IDs.
